<!-- <template>
    <div>
        <h1>Sign In for either</h1>
<!-- SO HERE, IF CUSTOMER BUTTON PRESSED, SHOW CLIENT LOGIN STUFF -->
        <ClientLogin v-if="user" />
        <!-- THERE ARE FOUR OPTIONS FROM THE MAIN PAGE EXPLORE. THESE ARE CLIENT SIGN IN / SIGN UP, AND RESTAURANT SIGN IN / SIGN UP. FROM THE EXPLORE PAGE.
        THE SIGN IN BUTTONS WILL GO TO CLIENT SIGN IN OR RESTAURANT AND DIRECT YOU TO THE SIGN IN / SIGN UP, DEPENDING ON WHO YOU ARE AND WHAT YOU'RE DOING. THE VIEW
        PAGE WOULD CALL THE API COMPONENT BASED ON WHO AND WHAT THE USER IS TRYING TO DO.
        SO, THE SIGN IN BUTTON CALLS THE SIGN IN CARD. EXPLORE -> CLIENT SIGNUP BUTTON -> TAKES YOU TO CLIENT SIGN IN VIEW, WHICH CALLS SIGN IN CARD -->
    </div>
<!-- </template>

<script>
export default {
    name: "SignIn",
    components: {
        ClientLogin,
        RestLogin
    },

}
</script>

<style scoped>

</style> --> -->